### ISSUE TITLE
Profile details feedback

### ISSUE THREAD

**Issue by innocenzi** [LumenoDev/bugs#1]
Hey Matt, I just registered on Lumeno, started filling my profile, and I have a few UX-related feedback: 

- On `/account`, I tried filling my cover letter at the bottom of the page. When updating, I got validation errors in the Location tab, which I hadn't even seen yet. I think I should be able to save the blocks one by one. After filling the Location tab, the same happens for the next tab.

- In the Location tab, I don't know how to fill Area and Coordinates.
	- Area doesn't correspond to anything in France as far as I know, so not sure what to put there. I tried "PACA" which corresponds to my region in France, but the field expects minimum 5 characters.
	- Coordinates are auto-filled when clicking the icon, but it's kind of hidden. Also, no one knows their coordinates, a map would be better.
	- The time zone could be auto-selected when filling the country field.

- In the Financial tab, the minimum income field doesn't specify if it should be gross or net.

**Comment by mattkingshott** [comment]
Thanks Enzo.

I'll look into making these changes / adding comments and report back :)

**Comment by mattkingshott** [comment]
Hey Enzo,

See my feedback:

> On `/account`, I tried filling my cover letter at the bottom of the page. When updating, I got validation errors in the Location tab, which I hadn't even seen yet. I think I should be able to save the blocks one by one. After filling the Location tab, the same happens for the next tab.

Agreed. Changed this.

> In the Location tab, I don't know how to fill Area and Coordinates. Area doesn't correspond to anything in France as far as I know, so not sure what to put there. I tried "PACA" which corresponds to my region in France, but the field expects minimum 5 characters.

I've added some clarification & examples on the page, and updated the docs. It should be town or city, followed by county, state or province.

> Coordinates are auto-filled when clicking the icon, but it's kind of hidden. Also, no one knows their coordinates, a map would be better.

I'll consider adding a map, and I've also given some help on finding out your coordinates if you don't have the hardware chip required. However, when you say it's "kind of hidden", what are you referring to?

> The time zone could be auto-selected when filling the country field.

Some countries have multiple time zones e.g. United States has EST, CST, PST. Therefore we can't assign a time zone by default.

> In the Financial tab, the minimum income field doesn't specify if it should be gross or net. 

This has been fixed and includes a note that it should be gross income.

**Comment by mattkingshott** [comment]
Great! Thanks man :)

If you find anything else, please don’t hesitate to let me know :)
