### ISSUE TITLE
UX, Make it easier to find your profile

### ISSUE THREAD

**Issue by caendesilva** [LumenoDev/bugs#11]
This issue was originally going to be called "Do I have a profile?" because I couldn't find it. I think being able to preview your public profile is important, so it shouldn't be "hidden" under the account settings.

**Comment by caendesilva** [comment]
While on the subject of profiles, I think it'd be cool to be able to edit profile settings on your profile as that lets you instantly visualize what it's going to look like.

**Comment by mattkingshott** [comment]
Thanks.

I've added a link to the public profile on the main dashboard (next deployment).

As for the second point, I'll make a note about in-place editing of your public profile as it is a nice idea, but I'm not sure when I'll be able to add that.
