### ISSUE TITLE
Had some trouble finding 'The Netherlands' as a country

### ISSUE THREAD

**Issue by bryantebeek** [LumenoDev/bugs#12]
It's pretty specific, I know, but I'm not used to seeing The Netherlands fall under the 'T'. Took me a bit to find it 😜

**Comment by mattkingshott** [comment]
So, would you expect simply 'Netherlands'?

**Comment by bryantebeek** [comment]
Yes 👍

**Comment by mattkingshott** [comment]
Okay. I'll change it.
