### ISSUE TITLE
Clicking the 'Find my coordinates' without specifying a location first, just gives a grey box with a console error

### ISSUE THREAD

**Issue by bryantebeek** [LumenoDev/bugs#13]
I'd expect to pick a location on the map when it opens. Maybe it should show a message to search my location first using the input.

![CleanShot 2022-07-03 at 12 38 49@2x](https://user-images.githubusercontent.com/2136273/177035914-e9e95d6b-3dc2-459e-9e2e-56c7a2af5fe0.png)
![CleanShot 2022-07-03 at 12 39 04@2x](https://user-images.githubusercontent.com/2136273/177035915-aab8859b-e44c-497b-a2a4-e7e10df8a167.png)

**Comment by mattkingshott** [comment]
Nice catch. I'll fix that before release next week. Thanks!
