### ISSUE TITLE
The 'user guide' link in the 'Add skill' modal should open a new page

### ISSUE THREAD

**Issue by bryantebeek** [LumenoDev/bugs#16]
I filled in the details on my new skill and saw the notice about the user guide. When I clicked the link I was redirected in the same tab and therefore was not able to add my skill as expected. 👍

![CleanShot 2022-07-03 at 13 31 19@2x](https://user-images.githubusercontent.com/2136273/177037566-c9cce83a-5a6b-41a2-8fb1-7dca05941145.png)

**Comment by mattkingshott** [comment]
Thanks. I'll change that.
