### ISSUE TITLE
[UX] 'Articles' tab of a user's profile page opens a new tab

### ISSUE THREAD

**Issue by bryantebeek** [LumenoDev/bugs#17]
Heey @mattkingshott, 

Would it be possible to show a user's articles under the tab instead of opening a new tab with a filter on the global articles page?

![CleanShot 2022-07-03 at 20 49 15@2x](https://user-images.githubusercontent.com/2136273/177053291-884819fe-2233-4b00-857e-64b1d18091bb.png)

**Comment by mattkingshott** [comment]
Hey. This was done for performance reasons originally. But I’ll have a look and see if this can be done efficiently :)
