### ISSUE TITLE
Date picker freezes site when creating a workplace.

### ISSUE THREAD

**Issue by jringeisen** [LumenoDev/bugs#2]
Hey Matt, when trying to select a start date when creating a new workplace the page freezes. It won't allow me to select a date. I don't see any errors in the console.

Browser: Chrome, Safari
OS: MacOs Monterray
url: https://lumeno.dev/workplaces

**Comment by mattkingshott** [comment]
Hey Jonathon,

Thanks for sharing this...

Unfortunately, I cannot replicate it. This my exact setup as well. Tested it in both Safari and Chrome.

Does it happen if you do a hard refresh on the workplaces page?
Are there any extensions that might be causing an issue?

Best,
Matt

**Comment by jringeisen** [comment]
@mattkingshott hmmm.... tried to do a hard refresh and cleared out my cache to see if maybe that was causing the issue. Still not working.

Here's a screen recording, not that it's going to be that helpful.
https://user-images.githubusercontent.com/7864804/166678072-f0a0e2ff-4e01-44ba-9118-da813462d7d9.mov

**Comment by jringeisen** [comment]
@mattkingshott I also disabled all browser extensions and still hasn't fixed the issue.

**Comment by mattkingshott** [comment]
Thanks for sharing the video... it's really weird as I can't replicate it and no else has reported any issues.

So, my guess is something is going on with the JS which is causing it to hang. Under the hood, the component uses the Pikaday library, which is pretty stable.

What version of Chrome are you using? Doubt that it matters, but thought I'd ask...

**Comment by jringeisen** [comment]
@mattkingshott I'm pretty OCD about keeping everything up to date. I'll keep playing around see if I can figure out what's going on.

Chrome Version: Version 100.0.4896.127 (Official Build) (arm64)
Mac OS Version: 12.3.1 (21E258)

**Comment by mattkingshott** [comment]
Thanks man, appreciate it!

Just for reference, here's mine: 

Chrome Version: 101.0.4951.54 (Official Build) (x86_64)
Mac OS Version: 12.3.1 (21E258)

I only upgraded to v101 this morning and it ran perfectly fine before. 

I doubt it's relevant, but is arm64, Apple Silicon / M1? Could that be an issue...

**Comment by mattkingshott** [comment]
Actually just checked with a friend and Apple Silicon works fine too. Also v101.

**Comment by jringeisen** [comment]
@mattkingshott tried what you said above, still not working. I relaunched Chrome to update to v101 and it's still not working. I don't know what else to try at this point lol.

**Comment by jringeisen** [comment]
I tried it on my wifes computer thinking maybe it was something with my machine. She has a Macbook Air M1 2020 on version 12.2.1 and it doesn't work on her machine either. I only have M1 machines so I don't have anything else to test it on.

**Comment by mattkingshott** [comment]
Thanks for trying so hard on this. I really appreciate your patience 🙏🏻

I’m running out of ideas myself as I just did a live demo with a friend that has an m1. He did it in safari and chrome latest. Both worked. 

Does it fail in Safari too?

**Comment by jringeisen** [comment]
Tried my wife's intel iMac, still doesn't work. Yes, it's not working in Chrome or Safari for me.

**Comment by mattkingshott** [comment]
Okay. I have confirmed that several other people have been able to use it without issue. So, let's see if we can try and eliminate other issues...

Is there any DNS, blocking, or routing rules on your machines or router that could be an issue? Unlikely since I doubt the library is trying to phone home... but I thought I'd ask.

Are you able to use the Pikaday demo on the website: https://pikaday.com

Thank you for your patience.

**Comment by jringeisen** [comment]
Hey @mattkingshott, no DNS, blocking, or routing rules setup. I was able to successfully use the Pikaday demo without any issue.

**Comment by mattkingshott** [comment]
Hey!

Well, we’re getting somewhere. I wonder if it’s a compilation issue? I’m using rollup. Although it’s still strange that it works for some and not others when they have the same setup… 🤷🏻‍♂️

Maybe I’ll try it with a CDN build and see if it solves the problem. I’ll also review the component line by line just in case there’s something going on that I haven’t spotted. 

I’ll reply here when it’s up and running. Thanks for your patience buddy :)

**Comment by mattkingshott** [comment]
Hey,

So I went through the component and I think I may have found some code that could be the culprit. Not entirely sure as I wasn't experiencing the error, but I've pushed an update. Try doing a hard refresh and see if it works now 🙏🏻

Cheers,
Matt

**Comment by jringeisen** [comment]
@mattkingshott that did it! All good now.

**Comment by mattkingshott** [comment]
Fantastic!!! Thanks for your patience :)
