### ISSUE TITLE
Small UI issues

### ISSUE THREAD

**Issue by FoksVHox** [LumenoDev/bugs#4]
There are multiple places where there are scrollbars for no apparent reason. 

Stuff like the overview of projects:
<img width="203" alt="image" src="https://user-images.githubusercontent.com/37844753/168763859-d199dd8f-8aed-4470-87f8-122957182232.png">

At the bottom of the page:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/37844753/168763986-ca232e3c-1a2c-41da-acfe-a6f0ab09551a.png">

In the notification panel:
<img width="31" alt="image" src="https://user-images.githubusercontent.com/37844753/168764146-c2b3a37b-90ed-4df2-be44-092c8dceac10.png">

**Comment by mattkingshott** [comment]
Thanks for reporting this. May I ask what browser and OS you are using?

**Comment by FoksVHox** [comment]
> Thanks for reporting this. May I ask what browser and OS you are using?

Sorry for not including it, I'm using Windows 11 and a chrome based browser called Brave (Lastest version of both Windows 11 & Brave)

**Comment by mattkingshott** [comment]
Okay. I think this is likely to be a Windows issue. I'm on a Mac, so will have to look into it.

Thanks for reporting. I'll get back to you soon :)

**Comment by mattkingshott** [comment]
Okay, I believe this is now fixed. Would you mind checking? 

Thanks!

**Comment by FoksVHox** [comment]
It seems to be, thanks!
