### ISSUE TITLE
Feature, add abstract skills?

### ISSUE THREAD

**Issue by caendesilva** [LumenoDev/bugs#9]
I think the idea of adding tools as skills is cool, but I'd also like to be able to add abstract skills not related to tools like "webdesign", "security", "operations", etc.

**Comment by mattkingshott** [comment]
Thanks, but I won't be adding this as skills have to directly sync up with vacancy requirements e.g. a one-to-one match with the underlying tools. In that respect, "umbrella" skills won't work as everybody will have a different opinion of what they mean.

I suggest that you add these abstract skills to your cover letter 👍🏻

**Comment by caendesilva** [comment]
I understand! Thanks for the tip!
